In [1]:
#creating nd arrays
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1,2,3],[1,2,3],[6,7,8]])

array([[1, 2, 3],
       [1, 2, 3],
       [6, 7, 8]])

In [4]:
np.zeros((2,3)) #generally used for initializing

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3,5))  #by default data type is coming float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
a=np.ones((2,3,3,2))

In [14]:
a[0]

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.arange(5,16,2) #start stop step

array([ 5,  7,  9, 11, 13, 15])

In [27]:
#random
print(np.random.random((2,3)))
print(np.random.randint(low=2,high=30,size=(2,3)))

[[0.5389785  0.08322855 0.46012607]
 [0.17992468 0.21987472 0.31106534]]
[[21  4  8]
 [ 7 28 15]]


In [29]:
x=np.linspace(10,20,10,dtype='float') #from to no. of between numbers
#all the points are linearly spaced, sub any two no. get the same no.
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [19]:
x1=x.copy()
x1

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
#numpy is class so it has attributes n funxtions

In [21]:
#attributes

x.shape

(10,)

In [22]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
arr1.shape

(2, 2, 2)