In [52]:
import numpy as np

In [53]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5,6]).reshape(2,3)

#below ones are tensors
arr3=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [54]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

(5,)
(2, 3)
(2, 2, 2)
(2, 2, 2)


In [55]:
print(arr1)
print(arr2)
print(arr3)
print('\n\n',arr4)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
#for dimensions
arr3.ndim

3

In [57]:
#size for all element

print(arr1.size)
print(arr2.size)
print(arr3.size)

5
6
8


In [58]:
#itemsize for getting size of element in array
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)
#int stored

arr4=np.array([1.3,2.3,3.2,4.1,5.5,6.8,7.7,8.9]).reshape(2,-1)
print(arr4.itemsize)

8
8
8
8


In [59]:
#element datatype
print(arr1.dtype)
print(arr4.dtype)

int64
float64


In [60]:
#for converting data type
arr1=arr1.astype('float')
print(arr1.dtype)

float64


In [61]:
arr4.astype('int')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
arrt=np.array([1,2,3,4,5,-1,0],dtype='float')
print(arrt)

arrt=np.array([1,2,3,4,5,-1,0],dtype='complex')
print(arrt)

arrt=np.array([1,2,3,4,5,-1,0],dtype='bool')
print(arrt)

[ 1.  2.  3.  4.  5. -1.  0.]
[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j -1.+0.j  0.+0.j]
[ True  True  True  True  True  True False]


In [63]:
arrt=np.array([1,2,3,4,5,-1,0],dtype='float')
print(arrt)
arrt=arrt.astype('bool')
print(arrt)

[ 1.  2.  3.  4.  5. -1.  0.]
[ True  True  True  True  True  True False]


In [64]:
#in data cleaning we also need to lessen the data footprint
#w do this by making the size lesser
#like age in float need to be convert into int as it takes less bytes
#and age in float makes no sense

In [65]:
#List vs Arrays
#faster
#convinient
#less memory

In [66]:
lista=list(range(100))
arra=np.arange(100)

In [67]:
import sys

print(sys.getsizeof(87)*len(lista))

print(arra.itemsize*arra.size)

2800
800


In [68]:
import time

x=range(10000000)
y=x=range(10000000,20000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b
print(time.time()-start_time)

2.8764989376068115
0.039328575134277344


In [69]:
arr5=np.arange(24).reshape(6,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
arr1

array([1., 2., 3., 4., 5.])

In [75]:
#slicing
print(arr1[2:4])
print(arr1[-1])
print(arr5[2])
print(arr5[:,2])
print(arr5[:,1:3])
print(arr5[2:4,1:3])

print(arr5[::5,::3]) #corner elements taken

[3. 4.]
5.0
[ 8  9 10 11]
[ 2  6 10 14 18 22]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 9 10]
 [13 14]]
[[ 0  3]
 [20 23]]


In [32]:
#iterations

for i in arr5:
  print(i)

for i in np.nditer(arr5):
  print(i)
#same functionality with flatten()
#for i in arr5.flatten():
#  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [14]:
#mathematical operation

In [19]:
a1=np.arange(1,21).reshape(5,4)
a2=np.arange(1,21).reshape(5,4)
print(a1)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [23]:
#scalar operation
#arithmetic
a1**2
a1+3
a1//4
a1/4

array([[0.25, 0.5 , 0.75, 1.  ],
       [1.25, 1.5 , 1.75, 2.  ],
       [2.25, 2.5 , 2.75, 3.  ],
       [3.25, 3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75, 5.  ]])

In [25]:
#relational

a1>10
a1==15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [29]:
#vector operation
#arithmetic

a1+a2
a1*a2
a1/a2 #these all are doing element wise , size shoul be same

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
#different functions
np.max(a1)
np.min(a1)
np.sum(a1)
np.product(a1)
#for doing col wise or row wise
np.max(a1,axis=0) #col
np.max(a1,axis=1) #row

array([ 4,  8, 12, 16, 20])

In [39]:
np.mean(a1,axis=0)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)

array([1.25, 1.25, 1.25, 1.25, 1.25])

In [40]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784, -0.28790332],
       [-0.96139749, -0.75098725,  0.14987721,  0.91294525]])

In [41]:
a1.shape,a2.shape

((5, 4), (5, 4))

In [44]:
np.dot(a1,a2.T)

array([[  30,   70,  110,  150,  190],
       [  70,  174,  278,  382,  486],
       [ 110,  278,  446,  614,  782],
       [ 150,  382,  614,  846, 1078],
       [ 190,  486,  782, 1078, 1374]])

In [46]:
np.log(a1)
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08]])

In [50]:
np.round(np.random.random((5,6))*100)
np.floor(np.random.random((5,6))*100)
np.ceil(np.random.random((5,6))*100)

array([[25., 70., 80., 53., 61., 18.],
       [17., 71., 70., 22., 95., 98.],
       [24., 70., 22., 60., 59., 74.],
       [65., 62., 69.,  9., 83., 66.],
       [91.,  6., 81., 32., 56., 36.]])

In [79]:
#transpose
np.transpose(a1)#or
a1.T
#ravel for convert to 1d
a1.ravel() #or
a1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [90]:
#stacking

#horizontal
np.concatenate((a1,a2),axis=1) #or
np.hstack((a1,a2))

#vertical
np.concatenate((a1,a2),axis=0) #or
np.vstack((a1,a2))

#shapr should be same to stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [97]:
#splitting
a=np.arange(1,17).reshape(4,4)
#horizontal
np.hsplit(a,2) #2 equal part split

#vertical
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [96]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])