In [ ]:
#creating nd arrays
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1,2,3],[1,2,3],[6,7,8]])

array([[1, 2, 3],
       [1, 2, 3],
       [6, 7, 8]])

In [ ]:
np.zeros((2,3)) #generally used for initializing

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,5))  #by default data type is coming float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(5,16,2) #start stop step

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
x=np.linspace(10,20,10) #from to no. of between numbers
#all the points are linearly spaced, sub any two no. get the same no.
x

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
x1=x.copy()
x1

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
#numpy is class so it has attributes n funxtions

In [ ]:
#attributes

x.shape

(10,)

In [ ]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr1.shape

(2, 2, 2)