In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5,6]).reshape(2,3)
arr3=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [3]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

(5,)
(2, 3)
(2, 2, 2)
(2, 2, 2)


In [4]:
print(arr1)
print(arr2)
print(arr3)
print('\n\n',arr4)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#for dimensions
arr3.ndim

3

In [6]:
#size for all element

print(arr1.size)
print(arr2.size)
print(arr3.size)

5
6
8


In [7]:
#itemsize for getting size of element in array
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)
#int stored

arr4=np.array([1.3,2.3,3.2,4.1,5.5,6.8,7.7,8.9]).reshape(2,-1)
print(arr4.itemsize)

8
8
8
8


In [8]:
#element datatype
print(arr1.dtype)
print(arr4.dtype)

int64
float64


In [9]:
#for converting data type
arr1=arr1.astype('float')
print(arr1.dtype)

float64


In [10]:
arr4.astype('int')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#in data cleaning we also need to lessen the data footprint
#w do this by making the size lesser
#like age in float need to be convert into int as it takes less bytes
#and age in float makes no sense

In [12]:
#List vs Arrays
#faster
#convinient
#less memory

In [13]:
lista=list(range(100))
arra=np.arange(100)

In [14]:
import sys

print(sys.getsizeof(87)*len(lista))

print(arra.itemsize*arra.size)

2800
800


In [15]:
import time

x=range(10000000)
y=x=range(10000000,20000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b
print(time.time()-start_time)

3.419046640396118
0.7490103244781494


In [16]:
arr5=np.arange(24).reshape(6,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
arr1

array([1., 2., 3., 4., 5.])

In [23]:
#slicing
print(arr1[2:4])
print(arr1[-1])
print(arr5[2])
print(arr5[:,2])
print(arr5[:,1:3])
print(arr5[2:4,1:3])

[3. 4.]
5.0
[ 8  9 10 11]
[ 2  6 10 14 18 22]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 9 10]
 [13 14]]


In [27]:
#iterations

for i in arr5:
  print(i)

for i in np.nditer(arr5):
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
